services:
  - type: web
    name: whats-fake-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    plan: free
    disks:
      - name: uploads
        mountPath: /opt/render/project/src/server/uploads
        sizeGB: 1
